<?php
/**
 * @file
 * Code for the hello_world feature.
 */

include_once 'hello_world.features.inc';

/**
 * Implementation of hook_node_view().
 *
 * Adds a message (saying "Content starts here!") before the node body by inserting
 * it into the $node object upon the node view operation. This ensures that the
 * message only appears on the 'hello_world_article' node type, and always before
 * the rest of the body. Also, add style overrides CSS file to all pages. This
 * could be in hook_init(), too, depending on how it's needed.
 */
function hello_world_node_view($node, $view_mode, $langcode) {
  // Show message before node content.
  if ($node->type == 'hello_world_article' && $view_mode == 'full') {
    $message = '<p><em>Content starts here!</em></p>';
    $node_body = isset($node->content['body'][0]) ? $node->content['body'][0]['#markup']: '';
    $node->content['body'][0]['#markup'] = $message . $node_body;
  }
  
  // Add CSS file.
  $options = array(
    'media' => 'screen',
    'weight' => 20
  );
  drupal_add_css(drupal_get_path('module', 'hello_world') . '/css/style-overrides.css', $options);
}
